### ISSUE TITLE
Typescript errors

### ISSUE THREAD

**Issue by doczoidberg** [oliver-moran/jimp#605] opened 2018-09-09 10:58 UTC
- Jimp Version: 0.4.0
-  Typescript: 2.8.3

I get the errrors when compiling in an angular 6.1 project:

```
ERROR in node_modules/jimp/jimp.d.ts(43,51): error TS1005: ';' expected.
node_modules/jimp/jimp.d.ts(45,9): error TS1005: ';' expected.
node_modules/jimp/jimp.d.ts(47,49): error TS1005: ',' expected.
node_modules/jimp/jimp.d.ts(48,24): error TS1005: ',' expected.
node_modules/jimp/jimp.d.ts(49,15): error TS1005: ']' expected.
node_modules/jimp/jimp.d.ts(49,23): error TS1005: ',' expected.
node_modules/jimp/jimp.d.ts(49,24): error TS1136: Property assignment expected.
```

**Comment by hipstersmoothie** [comment] 2018-09-09 21:52
Duplicate of #581 tracking typescript errors in that issue

**Closed by hipstersmoothie** 2018-09-09 21:52 UTC
