### ISSUE TITLE
Reading from buffer, and writing back to buffer doubles the size of the image

### ISSUE THREAD

**Issue by rcfrias** [oliver-moran/jimp#322] opened 2017-08-16 01:06 UTC
By using this library 
1) I receive an image as Base64 string
2) I convert it to binary using :

`var buffer = new Buffer(parsedBody.imageBase64.replace(/^data:image\/\w+;base64,/, ""),'base64');`

3) read the buffer using: 
`Jimp.read(buffer)`
4) do stuff like clone to generate a thumb, etc..
5) convert back to buffer using:
`var getBufferAsync = Promise.promisify(image.getBuffer, {context: image});`
Expected result: Converts to the original image.
Actual Result: This creates the right image, but with double of the size.
*By downloading the original buffer without reading it with Jimp, this downloads the correct image with the correct size.

Expected help: Explanation why this double size increase is happening ...
Any help appreciated! ^^

**Comment by hipstersmoothie** [comment] 2018-08-06 04:45
What mime type do you supply to getbuffer?

**Comment by hipstersmoothie** [comment] 2018-09-05 00:18
duplicate of #437

**Closed by hipstersmoothie** 2018-09-05 00:18 UTC
Labels: bug, duplicate
