### ISSUE TITLE
Parameter five in the function .print()

### ISSUE THREAD

**Issue by Drylotrans** [oliver-moran/jimp#436] opened 2018-04-23 00:11 UTC
How does the five parameter work in the .print() function?

```js
Jimp.loadFont(Jimp.FONT_SANS_8_BLACK).then(function (font) {
    image.print(font, x, y, str, width); // <--- 'width'
});
```

**Comment by hipstersmoothie** [comment] 2018-07-22 05:39
duplicate of #309

**Closed** 2018-07-22 05:39 UTC
