### ISSUE TITLE
Unable to open Buffer (TypeError: path must be a string or Buffer)

### ISSUE THREAD

**Issue by mufsir** [oliver-moran/jimp#180] opened 2016-10-25 11:48 UTC
When I try to read a buffer I get the following error.

> TypeError: path must be a string or Buffer

There is nothing wrong with the buffer as I can write that to a file.

**Comment by strandedcity** [comment] 2017-01-14 13:54
Would you be able to post sample code, or a specific problematic image illustrating the problem you're having?

**Comment by Manu-shukla** [comment] 2017-12-23 19:23
I am getting the same problem, but with different mean. I can't display image, it is just showing the buffered code and no image. I am basically doing it in node. So, any help? 
Please.

**Comment by hipstersmoothie** [comment] 2018-07-22 05:49
@Manu-shukla example code?

**Comment by hipstersmoothie** [comment] 2018-08-12 07:31
Feel free to open issues if they persist. Since no example code has ever been posted closing.

**Closed by hipstersmoothie** 2018-08-12 07:31 UTC
Labels: question

**Comment by ShirajG** [comment] 2019-11-28 19:37
I can reproduce this issue when trying to load an image from an S3 bucket. I can directly write the buffer to the response and it works, but when trying to pass the buffer to Jimp, I get the error `TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string or Buffer. Received type object`. Neither of the approaches below work. 

```  
s3.getObject({...bucketParams, ...{Key: `images/${req.params.image_id}`}},(error, data) => {
    if(!error) {
      originalImage = new Buffer.from(data.Body);
      Jimp.read(originalImage).then(image => {
        image.cover(200, 200);
        res.write(image);
        res.send();
      }).catch(err => {
        console.error(err);
      })
    } else {
      console.error(error);
    }
  })
```

```
app.get('/thumbnail/:image_id', (req, res) =>{
  s3.getObject({...bucketParams, ...{Key: `images/${req.params.image_id}`}},(error, data) => {
    if(!error) {
      originalImage = data.Body;
      Jimp.read(originalImage).then(image => {
        image.cover(200, 200);
        res.write(image);
        res.send();
      }).catch(err => {
        console.error(err);
      })
    } else {
      console.error(error);
    }
  })
});
```

console logging data.Body gives me: `<Buffer ff d8 ff e0 00 10 4a 46 49 46 00 01 01 01 00 48 00 48 00 00 ff db 00 43 00 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 ... 46326 more bytes>`
