### ISSUE TITLE
Image quality degrades after compositing

### ISSUE THREAD

**Issue by khyokhyo** [oliver-moran/jimp#365] opened 2017-11-13 09:45 UTC
The original image is -
![main_512x512](https://user-images.githubusercontent.com/19402631/32719007-18cc5abc-c889-11e7-8fbc-b1771525b144.jpg)

After compositing it looks like - 
![new](https://user-images.githubusercontent.com/19402631/32719368-535c6d4c-c88a-11e7-9dcc-9509333e05b6.jpg)

My code is : 

```
function getFormattedImage(url, width, height) {
  return new Promise((resolve, reject) => {
    new Jimp(width, height, 0xffffffff, async function(err, image) {
      if (err) {
        reject(err);
        return;
      }
      image.write('canvas.jpg', async function(err) {
        if (err) {
          reject(err);
          return;
        }
        const images = [url, 'canvas.jpg'];
        const jimps = [];
        for (let i = 0; i < images.length; i++) {
          jimps.push(Jimp.read(images[i]));
        }
        const data = await Promise.all(jimps);
        data[1].composite(data[0], 12, 12).write('new.jpg', async function(err) {
          if (err) reject(err);
          else {
            resolve();
          }
        });
      });
    });
  });
}
```
Why is this happening? Can you help?

TIA

**Comment by hipstersmoothie** [comment] 2018-08-12 06:01
@khyokhyo @riatzukiza @bruno-serfe

I can't really see whats wrong with the second image. can you point me towards whats wrong? also this might just be an issue with jpeg-js. 

Can you try just reading then immediately writing? Does the issue persist? If it does this is more likely a dupe of https://github.com/oliver-moran/jimp/issues/121 and not an issue with composite.

**Comment by hipstersmoothie** [comment] 2018-09-03 21:03
I think this is for sure a dup of #121 and has nothing to do with compositing. Closing in favor of #121

**Closed by hipstersmoothie** 2018-09-03 21:03 UTC
Labels: bug
