### ISSUE TITLE
Jimp.composite Error: w and h must be numbers

### ISSUE THREAD

**Issue by AlexT2** [oliver-moran/jimp#702] opened 2019-02-08 14:36 UTC
# Expected Behavior

Trying to composite 2 images with Jimp.composite

# Current Behavior

I get an error:
`
Error: w and h must be numbers
    at Jimp.throwError (/home/pi/bot/node_modules/@jimp/utils/dist/index.js:26:13)
    at Jimp.scanQuiet (/home/pi/bot/node_modules/@jimp/core/dist/index.js:1301:30)
    at Jimp.composite (/home/pi/bot/node_modules/@jimp/core/dist/composite/index.js:71:7)
    at /home/pi/bot/test.js:98:17
`

# Failure Information (for bugs)

`
Error: w and h must be numbers
    at Jimp.throwError (/home/pi/bot/node_modules/@jimp/utils/dist/index.js:26:13)
    at Jimp.scanQuiet (/home/pi/bot/node_modules/@jimp/core/dist/index.js:1301:30)
    at Jimp.composite (/home/pi/bot/node_modules/@jimp/core/dist/composite/index.js:71:7)
    at /home/pi/bot/test.js:98:17
`

## Context

- Jimp Version: 0.6.0
- Operating System: Linux raspberrypi 4.14.79-v7+ #1159 (raspberry pi 3 model b+)
- Node version: v10.15.1

**Comment by hipstersmoothie** [comment] 2019-02-13 02:14
Can i see some code @AlexT2?

**Comment by nihgwu** [comment] 2019-03-24 06:28
Got the same error while deploying on Netlify(Ubuntu Xenial 16.04), while it's ok in local (macOS Mojave 10.14.3)

**Comment by hipstersmoothie** [comment] 2019-03-30 00:01
Gonna need some reproduction code

**Comment by hipstersmoothie** [comment] 2019-04-27 16:45
Closing because no repro case. Will reopen if example code is supplied

**Closed by hipstersmoothie** 2019-04-27 16:45 UTC

**Comment by alexgman** [comment] 2019-08-19 16:40
You can reproduce this wiht the following code:

```
const stream = require('stream');
const Jimp = require('jimp');

const storage = require('azure-storage');
const blobService = storage.createBlobService();

module.exports = (context, myEvent, myBlob) => {

  const widthInPixels = process.env.THUMBNAIL_WIDTH;
  const blobName = myEvent.subject.split('/')[6];

    Jimp.read(myBlob).then((thumbnail) => {

        thumbnail.resize(widthInPixels, Jimp.AUTO);

        thumbnail.getBuffer(Jimp.MIME_PNG, (err, buffer) => {

            const readStream = stream.PassThrough();
            readStream.end(buffer);

            blobService.createBlockBlobFromStream('thumbnails', blobName, readStream, buffer.length, (err) => {
                context.done();
            });
        });

    }).catch(context.log);
};
```
