### ISSUE TITLE
Image rotation is anticlock-wise, not clockwise

### ISSUE THREAD

**Issue by GhosalkarPratik** [oliver-moran/jimp#669] opened 2018-11-29 13:24 UTC
Images rotating in the anti-clockwise direction

# Expected Behavior

Expected to rotate image clockwise, as per documentation.

# Current Behavior

But rotated anti-clockwise

## Steps to Reproduce

Run the following code with image 'download.jpg' attached below in the same folder
![image](https://user-images.githubusercontent.com/25661023/49224277-0a539b80-f407-11e8-8aab-4626d4b5af48.png)

```
'use strict';

var Jimp = require('jimp');

Jimp.read('download.jpg')
  .then(lenna => {
    return lenna
      .rotate(90)
      .write('lena-small-bw.jpg');
  });
```

Expected behaviour:
![image](https://user-images.githubusercontent.com/25661023/49224384-569edb80-f407-11e8-9cb2-a55d8ff6ad7c.png)

Actual behavior:
![image](https://user-images.githubusercontent.com/25661023/49224418-674f5180-f407-11e8-8989-2fb006b59d01.png)

## Context

- Jimp Version: 0.6.0
- Operating System: Windows 10
- Node version: 10.12.0
- NPM version: 6.4.1

**Comment by hipstersmoothie** [comment] 2018-11-29 19:18
duplicate of #631

**Closed by hipstersmoothie** 2018-11-29 19:18 UTC
