### ISSUE TITLE
Respecting EXIF orientation

### ISSUE THREAD

**Issue by dataxa** [oliver-moran/jimp#61] opened 2015-11-05 09:25 UTC
jimp.read(dir + images[i] , function(err , image){
			if(image.bitmap.width < 720 || image.bitmap.height < 960){
				throw "Source image too small";
			}
			if(image.bitmap.width / 720 > image.bitmap.height / 960){
				image = image.resize(jimp.AUTO , 960);
				image = image.crop((image.bitmap.width - 720 / 2) , 0 , 720 , 960);
			}else{
				image = image.resize(720 , jimp.AUTO);
				image = image.crop(0 , (image.bitmap.height - 960 / 2) , 720 , 960);
			}
			image.write(dir + "CR_" + images[i]);
		}); 

And output is 90 degrees rotated image.

**Comment by oliver-moran** [comment] 2015-11-05 10:31
Hi, @dataxa -

I think the issue is with this line:

```js
image = image.crop((image.bitmap.width - 720 / 2) , 0 , 720 , 960);
```

There might be an issue of garbage-in-garbage-out.

You say the width of the copped image should be 720px but you crop the image starting at an x position that is less than 360px from the edge.

Did you mean this instead:

```js
image = image.crop(image.bitmap.width - 720 , 0 , 720 , 960);
```

Let me know if this works. I'll add some kind of catch for this issue if that is what is going on.

**Comment by dataxa** [comment] 2015-11-05 12:44
I made very minimalistic sample and image still gets rotated:
```
var jimp = require("jimp");
var fs = require("fs");
var dir = "./src/lib/";
var images = fs.readdirSync(dir);
for(var i = 0 , l = images.length ; i < l ; i++){
	jimp.read(dir + images[i] , function(err , image){
		image.resize(jimp.AUTO , 960).write(dir + "CR_" + images[i]);
	}); 
}
```

**Comment by oliver-moran** [comment] 2015-11-05 12:52
I had to modify your code slightly to get it to run:

```js
var jimp = require("jimp");
var fs = require("fs");
var dir = "./src/lib/";
var images = fs.readdirSync(dir);
for(var i = 0 , l = images.length ; i < l ; i++){
	var out = dir + "CR_" + images[i];
    jimp.read(dir + images[i] , function(err , image){
        image.resize(jimp.AUTO , 960).write(out);
    }); 
}
```

I can't reproduce the issue.

Input:
![lenna](https://cloud.githubusercontent.com/assets/414918/10968830/0320a2b8-83bc-11e5-9051-8df0a27715ff.png)

Output:
![cr_lenna](https://cloud.githubusercontent.com/assets/414918/10968834/0d3e12a8-83bc-11e5-9747-b1bc2813a945.png)

**Comment by dataxa** [comment] 2015-11-05 13:00
There no relevant difference in the code. Here is the image I used: [before](http://www.upload.ee/image/5311820/test.jpeg)
And this is the result image: [after](http://www.upload.ee/image/5311821/CR_test.jpeg)

Windows 10
Node v4.1.1
Jimp 0.2.13

**Comment by oliver-moran** [comment] 2015-11-05 13:22
Windows appears to be rotating the image even before I run the Jimp script. When I save [this](http://www.upload.ee/image/5311820/test.jpeg) to my desktop, it is saved rotated.

Open the image in Windows Photo Viewer. Rotate it to the correct angle. Save it. Then try your resize script again in Jimp.

**Comment by dataxa** [comment] 2015-11-05 13:29
I tried to saved the image to my computer but it was not rotated like in your case.
I opened the JPEG file in photoshop and saved it as JPG and then jimp script worked.
The JPEG originates from iPhone 6 - looks like JIMP cant handle it.

**Comment by oliver-moran** [comment] 2015-11-05 13:44
Yes, it's the EXIF data.

The image (i.e. pixel data) is rotated 90 degrees and it contains data saying it is rotated 90 degrees. See the "Orientation" field in the EXIF data here and compare with how the image is shown on that site:

http://regex.info/exif.cgi?imgurl=http%3A%2F%2Fwww.upload.ee%2Fimage%2F5311820%2Ftest.jpeg

It's an interesting question: whether to go with the pixel data or to "fix" the image automagically when Jimp reads it.

Fixing it automatically may cause confusion too because my Windows 7 machine shows the file rotated (i.e. doesn't read the EXIF, just shows the pixels) whereas your Windows 10 machine shows the file upright (i.e. does read the EXIF and rotates the pixels).

**Comment by dataxa** [comment] 2015-11-05 15:57
Is there an easy way to convert EXIF to JIMP manageable format?

**Comment by oliver-moran** [comment] 2015-11-05 16:13
EXIF isn't so much a different format. It's just additional information.

After mulling it over, I think I'll update Jimp read the EXIF data and respect it. If the information is there then the likelihood is that respecting it leads to the most desirable outcome.

I'll aim to release an update in the next couple of days.

**Comment by dataxa** [comment] 2015-11-06 07:17
Thanks for help - much appreciated. Love the non-dependable plugin.

**Comment by oliver-moran** [comment] 2015-11-06 09:21
Fixed in the latest release published to NPM last night. I just tested it on Windows using the test code and images from above. All fine. Thanks for spotting this.

**Closed by oliver-moran** 2015-11-06 09:21 UTC

**Comment by pankajdx48** [comment] 2016-12-22 12:33
I write the code like this but i am not able to crop the image . 

var Jimp = require("jimp");

// open a file called "lenna.png"
var lenna = new Jimp("lenna.png", function () {
    this.resize(220, 220) // resize
        .write("lenna-small.png") // save
        .quality(60) // set JPEG quality
        .write("lenna-small.jpg") // save as JPEG
        .greyscale() // set greyscale
        .write("lena-small-bw.png") // save again
        .crop(80, 100, 80, 50) // crop
        .write("lena-small-bw-cropped.png"); // save again
});

**Comment by CapnSpellcheck** [comment] 2017-12-15 04:14
Does it read the Exif data in the input by default? I discovered a problem where I'm uploading jpeg, but after processing in jimp, the output does not appear correct. Input jpeg has Exif orientation tag ≠ 1.

**Comment by CapnSpellcheck** [comment] 2017-12-15 04:42
@oliver-moran Looking at this commit https://github.com/oliver-moran/jimp/commit/8bfdc9f6eebc01bfd9e500288f0991a44118e43b for the Exif orientation, the line index.js calling `exifRotate` I do not see in my installed version in node_modules. Instead I see this:
`                try { this._exif = EXIFParser.create(data).parse(); }
`
